name: build_latest

on:  
  push:
      branches: [ main ]
  workflow_dispatch:

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Parse semantic version
        id: parse_semver
        run: |
          full_version=`jq -r .version < frontend/package.json`
          major_version=`echo $full_version | cut -d'.' -f1`
          minor_version=`echo $full_version | cut -d'.' -f2`
          major_minor=`echo $major_version.$minor_version`
          echo ::set-output name=MAJOR_VERSION::$major_version
          echo ::set-output name=MAJOR_MINOR::$major_minor
          echo ::set-output name=FULL_VERSION::$full_version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: frontend
          push: true
          tags: |
            vaskozl/imagestored-frontend:latest
            vaskozl/imagestored-frontend:${{ steps.parse_semver.outputs.MAJOR_VERSION }}
            vaskozl/imagestored-frontend:${{ steps.parse_semver.outputs.MAJOR_MINOR }}
            vaskozl/imagestored-frontend:${{ steps.parse_semver.outputs.FULL_VERSION }}
          platforms: linux/amd64,linux/arm64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Parse semantic version
        id: parse_semver
        run: |
          full_version=`jq -r .version < backend/package.json`
          minor_version=`echo $full_version | cut -d'.' -f2`
          major_version=`echo $full_version | cut -d'.' -f1`
          major_minor=`echo $major_version.$minor_version`
          echo ::set-output name=MAJOR_VERSION::$major_version
          echo ::set-output name=MAJOR_MINOR::$major_minor
          echo ::set-output name=FULL_VERSION::$full_version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            vaskozl/imagestored-backend:latest
            vaskozl/imagestored-backend:${{ steps.parse_semver.outputs.MAJOR_VERSION }}
            vaskozl/imagestored-backend:${{ steps.parse_semver.outputs.MAJOR_MINOR }}
            vaskozl/imagestored-backend:${{ steps.parse_semver.outputs.FULL_VERSION }}
          context: backend
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
